server:
  port: 50001

sandbox:
  pool:
    java-size: 4
    cpp-size: 2
    python-size: 2
    acquire-timeout-ms: 3000
    max-use-count: 100 # 每个沙箱实例最大使用次数，避免生产环境每次请求都重建容器
    max-alive-ms: 1800000
    memory-bytes: 256000000
    cpu-count: 1
